### ISSUE TITLE
References for your implementation of Sea Clutter Simulation?

### ISSUE THREAD

**Issue by superzcf** [Mfarsh2000/sea_clutter#1]
Hey my friend, your implementation of Sea Clutter Simulation does help me a lot!  I really want to know the references of your implementation ORZ. Would you please share your reference my bro~

**Comment by Mfarsh2000** [comment]
See: Sea Clutter: Scattering, the K Distribution and Radar Performance
Book by Keith Ward, Robert J. A. Tough, and Simon Watts (second edition)

Right now there might be better methods (for coherent clutter) and also other distributions (see latest IEEE literature..)
